### ISSUE TITLE
missing maintainer

### ISSUE THREAD

**Issue by mediavrog** [en-japan/sbt-packer#2]
``` bash
➜  status-dashboard git:(13-deploy) ✗ sbt packerBuildAmi
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
[info] Loading project definition from /Users/maik_vlcek/workspace/status-dashboard/project
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.typesafe.sbt:sbt-native-packager:0.7.4 -> 1.0.0-M4
[warn] Run 'evicted' to see detailed eviction warnings
[info] Set current project to status-dashboard (in build file:/Users/maik_vlcek/workspace/status-dashboard/)
[info] Download Packer 0.7.5 at https://dl.bintray.com/mitchellh/packer/packer_0.7.5_darwin_amd64.zip
Exception in thread "Thread-1" java.io.IOException: Cannot run program "wget" (in directory "/Users/maik_vlcek/workspace/status-dashboard/target"): error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
    at sbt.SequentialProcess.runAndExitValue(ProcessImpl.scala:240)
    at sbt.CompoundProcess$$anonfun$1.apply$mcV$sp(ProcessImpl.scala:201)
    at sbt.Spawn$$anon$3.run(ProcessImpl.scala:17)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
    ... 4 more
[info] Wrote /Users/maik_vlcek/workspace/status-dashboard/target/scala-2.11/status-dashboard_2.11-1.0-SNAPSHOT.pom
[info] Building debian package with native implementation
[error] dpkg-deb: warning: parsing file '/Users/maik_vlcek/workspace/status-dashboard/target/status-dashboard-1.0-SNAPSHOT/DEBIAN/control' near line 11 package 'status-dashboard':
[error]  missing maintainer
[info] dpkg-deb: building package `status-dashboard' in `../status-dashboard_1.0-SNAPSHOT_all.deb'.
[error] dpkg-deb: warning: ignoring 1 warning about the control file(s)
java.lang.RuntimeException: No exit code: process destroyed.
    at scala.sys.package$.error(package.scala:27)
    at sbt.CompoundProcess$$anonfun$exitValue$1.apply(ProcessImpl.scala:193)
    at sbt.CompoundProcess$$anonfun$exitValue$1.apply(ProcessImpl.scala:193)
    at scala.Option.getOrElse(Option.scala:120)
    at sbt.CompoundProcess.exitValue(ProcessImpl.scala:193)
    at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
    at com.enjapan.sbt.packer.PackerPlugin$.getPacker(PackerPlugin.scala:103)
    at com.enjapan.sbt.packer.PackerPlugin$$anonfun$projectSettings$11$$anonfun$apply$1.apply(PackerPlugin.scala:58)
    at com.enjapan.sbt.packer.PackerPlugin$$anonfun$projectSettings$11$$anonfun$apply$1.apply(PackerPlugin.scala:58)
    at scala.Option.getOrElse(Option.scala:120)
    at com.enjapan.sbt.packer.PackerPlugin$$anonfun$projectSettings$11.apply(PackerPlugin.scala:58)
    at com.enjapan.sbt.packer.PackerPlugin$$anonfun$projectSettings$11.apply(PackerPlugin.scala:58)
    at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
    at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:packerCommand) No exit code: process destroyed.
[error] Total time: 23 s, completed Feb 2, 2015 7:07:41 PM
```

**Comment by mediavrog** [comment]
fixed by adding

`maintainer := "some name"`

to build.sbt
