### ISSUE TITLE
Fails to resolve json library with sbt 0.13.8

### ISSUE THREAD

**Issue by knshiro** [en-japan/sbt-packer#6]
Stacktrace:

```
java.lang.NoSuchMethodError: org.json4s.Formats.emptyValueStrategy()Lorg/json4s/prefs/EmptyValueStrategy;
[info]  at org.json4s.native.JsonMethods$class.render(JsonMethods.scala:29)
[info]  at org.json4s.native.JsonMethods$.render(JsonMethods.scala:62)
[info]  at com.enjapan.sbt.packer.PackerPlugin$$anonfun$projectSettings$11.apply(PackerPlugin.scala:70)
[info]  at com.enjapan.sbt.packer.PackerPlugin$$anonfun$projectSettings$11.apply(PackerPlugin.scala:66)
[info]  at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:35)
[info]  at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:34)
[info]  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[info]  at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
[info]  at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
[info]  at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
[info]  at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
[info]  at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
[info]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[info]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[info]  at java.lang.Thread.run(Thread.java:745)
```

**Comment by knshiro** [comment]
Fixed with ~~0.0.7~~ 0.0.8

**Comment by agastya71** [comment]
Hi:
   You mention that 0.0.7 fixes the problem, could you please elaborate on this ?  I am running into this issue while running a Spark Streaming job and using json4s to de-serialize a JSON string.
using version 3.2.11 of Json4s for scala 2_10 (2.10.4)  and Spark 1.5.1

your clarification is much appreciated.

Ramdev

**Comment by knshiro** [comment]
0.0.7 Doesn't use Json4s anymore, that's how I fixed the issue.

**Comment by knshiro** [comment]
Actually you can use 0.0.8 now.
